<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RunAnalyzersDuringLiveAnalysis>True</RunAnalyzersDuringLiveAnalysis>
    <PackageIcon>logo.png</PackageIcon>
    <Title>TicTacToe</Title>
    <ApplicationIcon>iconB.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="iconB.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\Documents\logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>